### ISSUE TITLE
Panic when running `docker system prune --all`

### ISSUE THREAD

**Issue by arisudesu** [amir20/dozzle#1317]
Dozzle is panicking when running `docker system prune --all` when having its web interface open. Can not reproduce when it isn't.

Backtrace is:
```
level=info msg="Dozzle version v3.7.0"
level=info msg="Accepting connections on :8080"
panic: runtime error: slice bounds out of range [:12] with length 0

goroutine 35 [running]:
github.com/amir20/dozzle/docker.(*dockerClient).Events.func1(0xc000352120, 0xc2a960, 0xc00029ec90, 0xc000063ec0)
        /dozzle/docker/client.go:208 +0x296
created by github.com/amir20/dozzle/docker.(*dockerClient).Events
        /dozzle/docker/client.go:194 +0xda
```

**Comment by amir20** [comment]
Nice find. I see where this could happen. Won’t have time to fix it for a while so I’ll leave it open.

**Comment by amir20** [comment]
Try master tag and see if it fixes it.

**Comment by arisudesu** [comment]
Seems to be fixed - can't reproduce with docker :master tag.
