### ISSUE TITLE
Search is broken 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#1881]
```
index.31ba9d2f.js:1 Error: Unknown message type
    at index.31ba9d2f.js:41:7742
    at Array.filter (<anonymous>)
    at wi.fn (index.31ba9d2f.js:41:7627)
    at wi.run (index.31ba9d2f.js:1:5254)
    at get value [as value] (index.31ba9d2f.js:1:13344)
    at N (index.31ba9d2f.js:1:12422)
    at Proxy.<anonymous> (index.31ba9d2f.js:41:21970)
    at pr (index.31ba9d2f.js:1:16741)
    at wi.G [as fn] (index.31ba9d2f.js:1:40108)
```

**Comment by amir20** [comment]
Fixed now
