### ISSUE TITLE
Constant blinking/reload of logs in the latest dozzle

### ISSUE THREAD

**Issue by SGudbrandsson** [amir20/dozzle#2891]
**Describe the bug**

**To Reproduce**

1. Go to dozzle
2. Select a container
3. Watch the whole thing reload time and time again

**Expected behavior**
Dozzle does not reload

**Screenshots**

![image](https://github.com/amir20/dozzle/assets/1608474/0cb44f59-35f5-43fa-bab9-6243eba593fc)

https://github.com/amir20/dozzle/assets/1608474/72cb1357-4aae-44f6-864f-d3892e3d0811

**Desktop (please complete the following information):**

- OS: Linux
- Docker version
```
Client:
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.20.12
 Git commit:        4debf41
 Built:             Mon Feb 12 00:00:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.20.12
  Git commit:       f417435
  Built:            Mon Feb 12 00:00:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.11
  GitCommit:        64b8a811b07ba6288238eefc14d898ee0b5b99ba
 runc:
  Version:          1.1.11
  GitCommit:        4bccb38cc9cf198d52bebf2b3a90cd14e7af8c06
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Browser & version https://www.whatsmybrowser.org/b/CTIZA
- Version v6.4.4

**If applicable include logs with `--level debug` and browser logs**
browser logs
```
Clearing messages for af9309069c23
main-Bf1ahSNp.js:45 Connecting to af9309069c23 with params {stdout: '1', stderr: '1'}
af9309069c23:40 
        
        
       GET https://logs.ed.traveldev.org/api/events/stream net::ERR_CONNECTION_CLOSED 200 (OK)
main-Bf1ahSNp.js:45 Clearing messages for af9309069c23
/api/hosts/localhost/containers/af9309069c23/logs/stream?stdout=1&stderr=1:1 
        
        
       GET https://logs.ed.traveldev.org/api/hosts/localhost/containers/af9309069c23/logs/stream?stdout=1&stderr=1 net::ERR_CONNECTION_CLOSED 200 (OK)
main-Bf1ahSNp.js:27 TypeError: Cannot read properties of undefined (reading 'stat')
    at t.value.statsHistory.map.x (main-Bf1ahSNp.js:45:62341)
    at Mn (main-Bf1ahSNp.js:27:46)
    at fi.l [as fn] (main-Bf1ahSNp.js:27:5732)
    at fi.run (main-Bf1ahSNp.js:23:1517)
    at _ (main-Bf1ahSNp.js:27:6100)
    at hi (main-Bf1ahSNp.js:23:2152)
    at cf (main-Bf1ahSNp.js:23:2676)
    at Jr (main-Bf1ahSNp.js:23:9789)
    at get value (main-Bf1ahSNp.js:23:9367)
    at jp (main-Bf1ahSNp.js:23:1689)
_1 @ main-Bf1ahSNp.js:27
lu @ main-Bf1ahSNp.js:27
Mn @ main-Bf1ahSNp.js:27
l @ main-Bf1ahSNp.js:27
run @ main-Bf1ahSNp.js:23
_ @ main-Bf1ahSNp.js:27
hi @ main-Bf1ahSNp.js:23
cf @ main-Bf1ahSNp.js:23
Jr @ main-Bf1ahSNp.js:23
get value @ main-Bf1ahSNp.js:23
jp @ main-Bf1ahSNp.js:23
get dirty @ main-Bf1ahSNp.js:23
get value @ main-Bf1ahSNp.js:23
jp @ main-Bf1ahSNp.js:23
get dirty @ main-Bf1ahSNp.js:23
_ @ main-Bf1ahSNp.js:27
hi @ main-Bf1ahSNp.js:23
cf @ main-Bf1ahSNp.js:23
Jr @ main-Bf1ahSNp.js:23
set value @ main-Bf1ahSNp.js:23
n.onopen @ main-Bf1ahSNp.js:43
main-Bf1ahSNp.js:27 TypeError: Cannot read properties of undefined (reading 'stat')
    at t.value.statsHistory.map.x (main-Bf1ahSNp.js:45:62214)
    at Mn (main-Bf1ahSNp.js:27:46)
    at fi.l [as fn] (main-Bf1ahSNp.js:27:5732)
    at fi.run (main-Bf1ahSNp.js:23:1517)
    at _ (main-Bf1ahSNp.js:27:6100)
    at hi (main-Bf1ahSNp.js:23:2152)
    at cf (main-Bf1ahSNp.js:23:2676)
    at Jr (main-Bf1ahSNp.js:23:9789)
    at set value (main-Bf1ahSNp.js:23:10243)
    at n.onopen (main-Bf1ahSNp.js:43:26340)
_1 @ main-Bf1ahSNp.js:27
lu @ main-Bf1ahSNp.js:27
Mn @ main-Bf1ahSNp.js:27
l @ main-Bf1ahSNp.js:27
run @ main-Bf1ahSNp.js:23
_ @ main-Bf1ahSNp.js:27
hi @ main-Bf1ahSNp.js:23
cf @ main-Bf1ahSNp.js:23
Jr @ main-Bf1ahSNp.js:23
set value @ main-Bf1ahSNp.js:23
n.onopen @ main-Bf1ahSNp.js:43
main-Bf1ahSNp.js:45 EventSource closed for af9309069c23
main-Bf1ahSNp.js:45 Clearing messages for af9309069c23
main-Bf1ahSNp.js:45 Connecting to af9309069c23 with params {stdout: '1', stderr: '1'}
```

Dozzle logs
```
time="2024-04-12T12:47:34Z" level=info msg="Dozzle version v6.4.4"
time="2024-04-12T12:47:34Z" level=debug msg="filterArgs = {map[]}"
time="2024-04-12T12:47:34Z" level=debug msg="Connected to local Docker Engine"
time="2024-04-12T12:47:34Z" level=info msg="Connected to 1 Docker Engine(s)"
time="2024-04-12T12:47:34Z" level=debug msg="subscribing to docker events from container store localhost"
time="2024-04-12T12:47:34Z" level=info msg="Accepting connections on :8080"
time="2024-04-12T12:47:36Z" level=debug msg="resetting timer for container stats collector localhost"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 2ba936035212"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 7204fc4f031d"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: b195327bc643"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 224d549f9039"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 352196da2b2e"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: eea889fc01a1"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: d87f4204a403"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 12c256a1923e"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 6fb9bec27d12"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 5b624f60f71d"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 1848328478d6"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: b8de87ebc0d8"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: b4c75ddbae4c"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: c590ae260bdc"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: f6aa7b006ef3"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 704165d897d6"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 40bfe2b8bdd2"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 09a987ce9ecc"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 94bc7a8f64cf"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: c8e769771794"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 4050d1b95942"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: dc787c9f8bd0"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 499d454b9b46"
time="2024-04-12T12:47:36Z" level=debug msg="subscribing to docker events from stats collector localhost"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 7e7e0f868655"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: de8c2ab758e1"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: f2488cdbb264"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 26feffbc9a37"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 06995a080139"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: c2047e0dc70e"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 7d564887cf45"
time="2024-04-12T12:47:36Z" level=debug msg="starting to stream stats for: 2f0200a526c7"
time="2024-04-12T12:47:38Z" level=debug msg="streaming logs for container" id=2ba936035212 since= stdType=all
time="2024-04-12T12:47:39Z" level=debug msg="context done, closing event stream"
time="2024-04-12T12:47:39Z" level=debug msg="scheduled to stop container stats collector localhost"
time="2024-04-12T12:47:39Z" level=debug msg="stream closed" id=2ba936035212
time="2024-04-12T12:47:39Z" level=debug msg="runtime mem stats" allocated="4.2 MB" routines=111 system="17 MB" totalAllocated="13 MB"
time="2024-04-12T12:47:40Z" level=debug msg="resetting timer for container stats collector localhost"
time="2024-04-12T12:47:40Z" level=debug msg="streaming logs for container" id=2ba936035212 since= stdType=all
time="2024-04-12T12:47:40Z" level=debug msg="Cache miss for []releases.Release"
time="2024-04-12T12:47:44Z" level=debug msg="stream closed" id=2ba936035212
time="2024-04-12T12:47:44Z" level=debug msg="runtime mem stats" allocated="5.2 MB" routines=114 system="17 MB" totalAllocated="16 MB"
time="2024-04-12T12:47:44Z" level=debug msg="context done, closing event stream"
time="2024-04-12T12:47:44Z" level=debug msg="scheduled to stop container stats collector localhost"
time="2024-04-12T12:47:46Z" level=debug msg="streaming logs for container" id=5b624f60f71d since= stdType=all
time="2024-04-12T12:47:47Z" level=debug msg="resetting timer for container stats collector localhost"
time="2024-04-12T12:47:47Z" level=debug msg="stream closed" id=5b624f60f71d
time="2024-04-12T12:47:47Z" level=debug msg="runtime mem stats" allocated="7.2 MB" routines=113 system="17 MB" totalAllocated="18 MB"
time="2024-04-12T12:47:47Z" level=debug msg="streaming logs for container" id=5b624f60f71d since= stdType=all
time="2024-04-12T12:47:49Z" level=debug msg="context done, closing event stream"
time="2024-04-12T12:47:49Z" level=debug msg="scheduled to stop container stats collector localhost"
time="2024-04-12T12:47:49Z" level=debug msg="stream closed" id=5b624f60f71d
time="2024-04-12T12:47:49Z" level=debug msg="runtime mem stats" allocated="4.7 MB" routines=112 system="21 MB" totalAllocated="20 MB"
time="2024-04-12T12:47:52Z" level=debug msg="resetting timer for container stats collector localhost"
time="2024-04-12T12:47:52Z" level=debug msg="streaming logs for container" id=5b624f60f71d since=1712926067539 stdType=all
time="2024-04-12T12:47:52Z" level=debug msg="stream closed" id=5b624f60f71d
time="2024-04-12T12:47:52Z" level=debug msg="runtime mem stats" allocated="7.0 MB" routines=113 system="21 MB" totalAllocated="22 MB"
time="2024-04-12T12:47:53Z" level=debug msg="streaming logs for container" id=5b624f60f71d since= stdType=all
time="2024-04-12T12:47:54Z" level=debug msg="context done, closing event stream"
time="2024-04-12T12:47:54Z" level=debug msg="scheduled to stop container stats collector localhost"
time="2024-04-12T12:47:54Z" level=debug msg="stream closed" id=5b624f60f71d
time="2024-04-12T12:47:54Z" level=debug msg="runtime mem stats" allocated="4.7 MB" routines=112 system="21 MB" totalAllocated="24 MB"
time="2024-04-12T12:47:58Z" level=debug msg="resetting timer for container stats collector localhost"
time="2024-04-12T12:47:58Z" level=debug msg="streaming logs for container" id=5b624f60f71d since=1712926073000 stdType=all
time="2024-04-12T12:47:58Z" level=debug msg="stream closed" id=5b624f60f71d
time="2024-04-12T12:47:58Z" level=debug msg="runtime mem stats" allocated="6.7 MB" routines=113 system="21 MB" totalAllocated="26 MB"
time="2024-04-12T12:47:58Z" level=debug msg="streaming logs for container" id=5b624f60f71d since= stdType=all
time="2024-04-12T12:47:58Z" level=debug msg="stream closed" id=5b624f60f71d
time="2024-04-12T12:47:58Z" level=debug msg="runtime mem stats" allocated="8.3 MB" routines=113 system="21 MB" totalAllocated="27 MB"
time="2024-04-12T12:47:58Z" level=debug msg="context done, closing event stream"
time="2024-04-12T12:47:58Z" level=debug msg="scheduled to stop container stats collector localhost"
```

**Comment by amir20** [comment]
Do you have a proxy? Could be related to https://github.com/amir20/dozzle/issues/2887

**Comment by amir20** [comment]
Also did this happen recently?

**Comment by SGudbrandsson** [comment]
Yes, I have a proxy, Traefik.

This was the latest [v2.11.2](https://github.com/traefik/traefik-library-image/blob/20b8a58e55e1874939af980a52ba353c4fad32c5/alpine/Dockerfile) version, so I tried downgrading to 2.10.X and that worked.

Sorry for the false alarm and thanks for the quick response and awesome app!!
